nydus-image: support generate tarfs bootstrap from tar stream via stdin
dragonflyoss/image-service pull request #1204
Opened 2023-04-10 08:16 UTC by kevinXYin

Add '--blob-stdin-tar-stream' option to 'nydus-image create -t tar-tarfs' to generate tarfs bootstrap from tar stream via stdin instead of SOURCE tar file.

2023-04-12 14:57 UTC, jiangliu commented
How about using FIFO instead of stdin? Once nydus-image reads prefetch list from stdin, so it would be better to use FIFO instead.

2023-04-13 06:45 UTC, imeoer commented
> How about using FIFO instead of stdin? Once nydus-image reads prefetch list from stdin, so it would be better to use FIFO instead.

+1

2023-04-14 02:00 UTC, kevinXYin commented
> How about using FIFO instead of stdin? Once nydus-image reads prefetch list from stdin, so it would be better to use FIFO instead.

Thanks , I will try FIFO. And check if there is performance drop using FIFO compared to stdin, cause may need additional memory copies and interaction. I think we need to make image convert as fast as possible for tarfs usage.

2023-04-27 03:22 UTC, ccx1024cc requested changes
Please add e2e test cases for this new option

2023-06-12 07:21 UTC, closed without merging