Implement nydusd and nydus-snapshotter to deliver config through the socket API
dragonflyoss/image-service pull request #1379
Opened 2023-07-20 02:50 UTC by DarkMountain-wyz

## Relevant Issue (if applicable)
https://github.com/containerd/nydus-snapshotter/issues/388

## Details
- The previous PR has been closed, so a new PR has been submitted
- Command line parameter --config now represents the URL to request daemon config from nydus-snapshotter.
- New command line parameter --config-source, representing the unix socket path for communication between nydus snapshot and nydusd.
- Nydusd is now requesting config information from nydus-snapshotter instead of obtaining config by reading the config dump file.

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2023-07-31 02:15 UTC, imeoer commented on src/bin/nydusd/main.rs
> +                    let socket_path = match args.value_of("config-source") {
Does the option `--config-source` should be conflict with `--config`, right?

2023-07-31 02:15 UTC, imeoer commented on src/bin/nydusd/main.rs
> +fn send_unix_socket_request(socket_path: &str, method: &str, url: &str) -> Option<String> {
How about putting this into `api/src/config.rs`, and naming it `fn from_source(...)`.

2023-07-31 02:15 UTC, imeoer commented on src/bin/nydusd/main.rs
> +        None => return None,
We'd better return a `Result` instead of an `Option`, and handle the `Result` outside.

2023-07-31 02:15 UTC, imeoer commented on src/bin/nydusd/main.rs
> +    let request = format!("{} {} HTTP/1.1\r\nHost: localhost\r\n\r\n", method, url);
How about using the `hyper::Client` crate directly, instead of implementing the HTTP over the unix domain socket client by self?

2023-08-07 02:54 UTC, imeoer commented on api/src/config.rs
> +    /// Fill backend config from nydus-snapshotter
Not only for nydus snapshotter in the future.

2023-08-07 02:54 UTC, imeoer commented on api/src/config.rs
> +        let buf = hyper::body::to_bytes(response).await?;
Should read the response body after the status code check.

2023-08-07 02:54 UTC, imeoer commented on api/src/config.rs
> +                "Request failed with status code: {}",
`failed to request backend config from source, status code: {}`

2023-08-07 02:54 UTC, imeoer commented on api/src/config.rs
> +        info!("你到这了吗");
Remove this.

2023-08-07 02:54 UTC, imeoer commented on src/bin/nydusd/main.rs
> +        Arg::new("credential-source")
How about renaming it to `backend-source`, and combining the url with `systemsock`?

2023-08-07 06:22 UTC, adamqqqplay commented
Could you add some unit tests to cover your changes? Thanks!

2023-08-08 02:00 UTC, imeoer commented
@DarkMountain-wyz Please refine the commits and add some commit messages to explain why & how to do this.

2023-08-08 02:04 UTC, DarkMountain-wyz commented
> @DarkMountain-wyz Please refine the commits and add some commit messages to explain why & how to do this.

2023-09-25 03:37 UTC, imeoer commented
@DarkMountain-wyz We'd better refresh the backend config when the registry auth expires.

2023-10-16 03:42 UTC, imeoer commented on api/Cargo.toml
> +anyhow = "1"
Maybe use the exact version `1.0` here?

2023-10-16 03:44 UTC, imeoer commented on api/Cargo.toml
> +tokio = { version = "1.24", features = ["full"] }
It seems the using of `full` feature will import a large number of dependencies, can we only use the necessary feature?

2023-10-16 03:49 UTC, imeoer commented on storage/src/backend/registry.rs
> +const MAX_RETRIES: u32 = 1;
It is unnecessary to add the retry mechanism because the upper caller will retry if any error happens.

2023-10-16 04:04 UTC, imeoer commented on api/src/config.rs
> +    pub static ref BACKEND_SOURCE_PATH: Mutex<Option<String>> = Mutex::new(None);
How about putting this into `BackendConfigV2` struct like this (as a private field, do not participate in Deserialize/Serialize):

```
pub struct BackendConfigV2 {
    /// Type of storage backend.
    #[serde(rename = "type")]
    pub backend_type: String,
    /// Source of storage backend configuration.
    #[serde(skip_serializing, skip_deserializing)]
    backend_source: Option<String>,
}
```

2023-10-16 04:07 UTC, imeoer commented on storage/src/backend/registry.rs
> +            } else if token_resp.status() == StatusCode::FORBIDDEN && retries < MAX_RETRIES {
Should be `vec![StatusCode::UNAUTHORIZED, StatusCode::FORBIDDEN].contains(&token_resp.status())`.

2023-10-16 04:09 UTC, imeoer commented on storage/src/backend/registry.rs
> +                            username = new_username;
`self.username` & `self.password` should be updated.

2023-10-30 03:05 UTC, ccx1024cc requested changes

2023-10-30 03:05 UTC, ccx1024cc commented on src/bin/nydusd/main.rs
> +            Arg::new("backend-source")
Smoke test is required. Please also update doc.

2023-11-01 04:07 UTC, bergwolf reviewed
The PR title mentions config delivery but it actually is only about auth right? We already support configurating nydusd backend (which including auth info) via API. It is just that we need to amend nydus-snapshotter to stopping passing config via local file but via API instead. @DarkMountain-wyz Are you planning to look at the nydus-snapshotter part as well?

2023-11-01 04:11 UTC, bergwolf commented
And where is the corresponding nydus-snapshotter part of the change? I assume we need a new API from snapshotter as well, no?

2023-11-01 06:55 UTC, DarkMountain-wyz commented
> And where is the corresponding nydus-snapshotter part of the change? I assume we need a new API from snapshotter as well, no?

The corresponding modification for the nydus-snapshotter can be found in the pull request [here](https://github.com/containerd/nydus-snapshotter/pull/504). The approach taken involves providing a domain socket API for nydusd to request and retrieve backend information. The decision to pass all backend information rather than just authentication details is to ensure flexibility in case new types of backends are added in the future, without needing to modify this interface.

2023-11-09 01:31 UTC, closed without merging