local cas: achieve chunk deduplication for nydus.
dragonflyoss/image-service pull request #1399
Opened 2023-08-09 03:59 UTC by xwb1136021767

## Relevant Issue (if applicable)
_If there are Issues related to this PullRequest, please list it._

## Details
Original version from https://github.com/dragonflyoss/image-service/pull/956.
The previous version of local cas was static dedup, which only modified the chunk information in bootstrap. There is a serious problem: it may reuse chunks that cannot be obtained by the backend of the current image, resulting in the container being unable to load the corresponding chunk data on demand during runtime. To address this issue, dynamic dedup was introduced. When nydusd initializes the blob cache, it reads the corresponding backend configuration information of the blob from the CAS database, enabling the blob cache to read chunk data from other backend.

What's more, the mismatch between dynamic dedup and nydus' chunk amplification can result in a larger cache size after dedup than without dedup. Because chunk amplification can cause reused chunks to be pulled multiple times, resulting in a larger cache size after dedup is enabled than when dedup is not enabled. To address this issue, a dedup_bitmap was introduced. When initializing rafs, dedup_bitmap is generated based on the chunk information in blob. The determination of whether a chunk in a blob is ready requires both the chunk map and deduplication bitmap to make a joint decision.

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2023-08-09 09:43 UTC, adamqqqplay commented on Cargo.lock
> -
Maybe xattr changes in Cargo.lock could merge to first commit?

2023-10-24 06:48 UTC, imeoer commented
@xwb1136021767 Sorry for the delayed reply, please help to add some docs about background and usage for users.

2023-10-30 02:43 UTC, ccx1024cc requested changes

2023-10-30 02:43 UTC, ccx1024cc commented on api/src/config.rs
> +    pub deduplication: Option<DeduplicationConfigV2>,
Please add [smoke test](https://github.com/dragonflyoss/nydus/tree/master/smoke/tests) and update [doc](https://github.com/dragonflyoss/nydus/tree/master/docs)

2023-10-30 02:43 UTC, ccx1024cc commented on builder/src/core/bootstrap_dedup.rs
> +                    n.lock_node().dedup_chunk_for_node(
`get_chunk_ofs` seems not implemented with v5. Is `dedup_chunk_for_node` able to work with v5? If not please use `is_v6` to avoid it.

2023-10-30 02:43 UTC, ccx1024cc commented on src/bin/nydus-image/main.rs
> +            App::new("dedup")
Smoke test is required. Please also update test doc.

2023-10-30 02:43 UTC, ccx1024cc commented on storage/src/device.rs
> +    fn test_serialize_cipher_object() {
Assertions is necessary that ensures cipher ok.

2023-10-30 02:43 UTC, ccx1024cc commented on storage/src/device.rs
> +            println!(
Please remove these debug information for merge

2023-11-06 16:08 UTC, isidentical commented
This is a particularly cool feature that I think would benefit everyone who deals with multiple random images that essentially share the same stuff thats used at runtime (e.g. `libpython3.so`) but built by different methodologies (different base images etc) and would optimize cold starts in a very intriguing way. Any chance on knowing what are the next steps for this PR to get streamlined aside from the existing reviews (which all seems easily addressable, so am not sure if they are a blocker)? Is the concept itself is OK for nydus maintainers? Are there any help needed which I could contribute to (am not super knowledgeable on nydus side, but would be happy to dive deep into fixing the easy stuff like the existing reviews) to push this forward?

2023-11-20 06:50 UTC, imeoer commented
@xwb1136021767 Can we also give a performance test result in the doc to give users confidence?

2023-11-23 15:57 UTC, jiangliu commented on utils/Cargo.toml
> +rusqlite = { version = "0.29.0", features = ["bundled"] }
please update to latest "0.30.0".

2023-11-23 16:02 UTC, jiangliu commented on utils/src/cas.rs
> +            "CREATE INDEX IF NOT EXISTS BlobIndex_V5 ON BlobInfos_V5(BlobId)",
`BlobInfos_V5(BlobId)` is a primary key, should it have already been indexed?

2023-11-23 16:05 UTC, jiangliu commented on utils/src/cas.rs
> +            BlobId            TEXT NOT NULL,
Should we use an auto-incr integer as primary key for BlobInfos_V5, so we can store an integer instead of a text here.

2023-11-24 02:15 UTC, jiangliu commented on utils/src/cas.rs
> +        println!("v5 blobs");
The `println!` lines should be removed

2023-11-27 01:05 UTC, jiangliu commented
> This is a particularly cool feature that I think would benefit everyone who deals with multiple random images that essentially share the same stuff thats used at runtime (e.g. `libpython3.so`) but built by different methodologies (different base images etc) and would optimize cold starts in a very intriguing way. Any chance on knowing what are the next steps for this PR to get it streamlined aside from the existing reviews (which all seems easily addressable, so am not sure if they are a blocker)? Is the concept itself is OK for nydus maintainers? Are there any help needed which I could contribute to (am not super knowledgeable on nydus side, but would be happy to dive deep into fixing the easy stuff like the existing reviews) to push this forward?

This idea is warmly welcomed:) 
The only issue is a little bigger for review, will put more effort on this.

2023-11-28 06:19 UTC, jiangliu commented
@xwb1136021767 When reviewing the PR, I have worked out some enhancements/fixes over your work. How about holding on for while, then I will try to submit my patches to your repo?

2023-11-28 06:31 UTC, xwb1136021767 commented
> @xwb1136021767 When reviewing the PR, I have worked out some enhancements/fixes over your work. How about holding on for while, then I will try to submit my patches to your repo?

Thank you so much for your help!

2023-11-29 00:47 UTC, imeoer commented on api/src/config.rs
> +    pub fn get_enable(&self) -> bool {
It's a pub field, still need this? Also better be `is_enable`.

2023-11-29 00:49 UTC, imeoer commented on api/src/config.rs
> +    /// Work fir for image dedup
typo `dir`.

2023-11-29 00:50 UTC, imeoer commented on builder/src/core/bootstrap.rs
> +#![allow(unused_variables, unused_imports)]
Why we need this.

2023-11-29 01:39 UTC, imeoer commented on builder/src/core/bootstrap.rs
> +        //rewrite blob table
Ditto.

2023-11-29 02:13 UTC, imeoer commented
I can't understand why we need to rebuild a new bootstrap, can we do runtime de-duplication by enhancing the blob cache? i.e. for example using a global `(chunk_digest, chunk_info)` db records.

2023-11-29 02:14 UTC, imeoer requested changes
I can't understand why we need to rebuild a new bootstrap, can we do runtime de-duplication by enhancing the blob cache? i.e. for example using a global (chunk_digest, chunk_info) db records.

2023-11-29 02:46 UTC, xwb1136021767 commented
> I can't understand why we need to rebuild a new bootstrap, can we do runtime de-duplication by enhancing the blob cache? i.e. for example using a global (chunk_digest, chunk_info) db records.

I have also considered the solution you mentioned before. My previous concern was whether runtime deduplication would make the CAS database a performance bottleneck in IO intensive scenarios. There are indeed problems with the current solution, and personally, I think the biggest problem is how to combine it with the GC mechanism of the image, especially in localfs or localdisk mode, because nydus snapshot cannot prevent the deletion operation of the image.

2023-11-29 03:08 UTC, imeoer commented
> I have also considered the solution you mentioned before. My previous concern was whether runtime deduplication would make the CAS database a performance bottleneck in IO intensive scenarios. There are indeed problems with the current solution, and personally, I think the biggest problem is how to combine it with the GC mechanism of the image, especially in localfs or localdisk mode, because nydus snapshot cannot prevent the deletion operation of the image.

This may require some testing, full dedup and rebuilding the whole bootstrap (not only chunk infos?) on booting may also affect cold start performance. Either full dedup or on-demand dedup, there will be GC issues as containerd checks if an image is referencing a blob based on the image manifest, references:

https://github.com/containerd/nydus-snapshotter/blob/5009c522df583cdf76ee37ae2a3c6440d5d79797/snapshot/snapshot.go#L583

https://github.com/containerd/nydus-snapshotter/blob/5009c522df583cdf76ee37ae2a3c6440d5d79797/pkg/cache/manager.go#L70

2023-12-07 07:02 UTC, jiangliu commented
A simplified version to implement chunk deduplication at runtime instead of at build time.
#1507

2025-09-06 00:14 UTC, closed without merging