Takeover
dragonflyoss/image-service pull request #1487
Opened 2023-11-18 06:45 UTC by kevinXYin

## Relevant Issue (if applicable)
https://github.com/dragonflyoss/nydus/issues/1421

## Details
This is based on https://github.com/dragonflyoss/nydus/pull/1434 , make the takeover feature can support both fusedev and fscache mode.

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2023-11-20 03:22 UTC, ccx1024cc requested changes
Smoke test is required

2023-11-20 03:22 UTC, ccx1024cc commented on Cargo.toml
> +fuse-backend-rs = { git = "https://github.com/loheagn/fuse-backend-rs.git", branch = "vfs-persist" }
Use tag after published?

2023-11-20 03:22 UTC, ccx1024cc requested changes, later dismissed
Smoke test is required.

2023-11-26 12:08 UTC, kevinXYin commented on Cargo.toml
> +fuse-backend-rs = { git = "https://github.com/loheagn/fuse-backend-rs.git", branch = "vfs-persist" }
thanks, fix

2023-12-07 02:43 UTC, jiangliu commented on upgrade/src/backend/mod.rs
> +use std::{io, os::fd::RawFd};
Please add copyright header:)

2023-12-07 08:44 UTC, kevinXYin commented on upgrade/Cargo.toml
> +snapshot = { git = "https://github.com/firecracker-microvm/firecracker", tag = "v1.4.1" }
Thanks, fixed

2023-12-07 08:45 UTC, kevinXYin commented on upgrade/src/backend/mod.rs
> +use std::{io, os::fd::RawFd};
fixed

2023-12-07 08:55 UTC, jiangliu commented on src/bin/nydusd/api_server_glue.rs
> +                } else if let Some(mut mgr_guard) = self.get_daemon_object()?.upgrade_mgr() {
```
                } else {
                    if let Some(mut mgr_guard) = self.get_daemon_object()?.upgrade_mgr() {
                             mgr_guard.remove_blob_entry_state(&param.domain_id, &param.blob_id);
                    }
                    Ok(ApiResponsePayload::Empty)	                    Ok(ApiResponsePayload::Empty)
                }	                }
```

2023-12-07 09:51 UTC, jiangliu commented
Otherwise LGTM, thanks for the great work:)

2023-12-07 11:04 UTC, imeoer approved these changes
Thanks for the work, let's add a smoke test case for validating fusedev failover later cc @loheagn .

2023-12-07 11:24 UTC, hsiangkao approved these changes

2023-12-07 11:38 UTC, kevinXYin commented on upgrade/src/backend/mod.rs
> +    fn restore(&mut self, fds: &mut Vec<RawFd>, data: &mut Vec<u8>) -> Result<(usize, usize)>;
Thanks, fixed

2023-12-07 12:09 UTC, jiangliu approved these changes

2023-12-07 12:10 UTC, merged