Support runtime chunk deduplication
dragonflyoss/image-service pull request #1507
Opened 2023-12-07 02:10 UTC by jiangliu

## Details
This PR enhances `nydusd` to support runtime chunk deduplication. It works in this way:
1) Use a sqlite database to record information about decompressed/plaintext chunks available on local node.
2) When a chunk is not ready in the uncompressed data blob file, query the sqlite database whether a chunk with the same chunk digest is available. If a chunk with the same chunk digest exists, copy the decompressed from the source data blob file to the target data blob by using `copy_file_range()`.
3) Otherwise download the compressed chunk from remote, uncompress it and write to the target data blob, and add a record for the chunk to the database.

So there are two types of chunk deduplication:
1) saving network bandwidth when the chunk is available on local node, because we don't need to download compressed chunk data from remote.
2) saving local disk space if the underlying filesystem supports reference. If the filesystem storing data blob files supports reference, `copy_file_range()` will optimize to use reference instead of data copy, thus reduce local storage consuption.  

## Types of changes

_What types of changes does your PullRequest introduce? Put an `x` in all the boxes that apply:_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Go over all the following points, and put an `x` in all the boxes that apply._

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

2023-12-09 05:32 UTC, Desiki-high commented on smoke/tests/chunk_dedup.go
See https://go.dev/doc/tutorial/add-a-test, go test needs a file name like `xxxx_test.go`. How about renaming it to `chunk_dedup_test.go`.

2023-12-09 07:38 UTC, jiangliu commented on smoke/tests/chunk_dedup.go
Thanks for reminder, fixed.

2023-12-13 09:17 UTC, ccx1024cc commented on storage/src/cache/filecache/mod.rs
> +            let load_chunk_digest = need_validation || cas_mgr.is_some();
If ( open chunk deduplication ) = ( no validation ), better to stat in doc too.

2023-12-13 09:19 UTC, ccx1024cc reviewed
NICE. LGTM.
`copy_file_range` is triggered in tests. It's effective.

2023-12-13 09:27 UTC, ccx1024cc requested changes

2023-12-13 09:27 UTC, ccx1024cc commented on storage/src/cache/fscache/mod.rs
> +            blob_data_file_path = get_path_from_file(&file);
`get_path_from_file` is not recovered in tests. `cas_mgr` is empty?

[coverage(https://app.codecov.io/gh/dragonflyoss/nydus/pull/1507/blob/storage/src/utils.rs)

2023-12-13 09:36 UTC, ccx1024cc commented
> NICE. LGTM. `copy_file_range` is triggered in tests. It's effective.

Sorry, not LGTM. Doubt that copy_file_range is covered by ut, not by smoke case.
`get_path_from_file` is key path for fileEntry with cas manager. If smoke case works, then coverage is expected.

2023-12-13 09:39 UTC, ccx1024cc commented
> > NICE. LGTM. `copy_file_range` is triggered in tests. It's effective.
> 
> Sorry, not LGTM. Doubt that copy_file_range is covered by ut, not by smoke case. `get_path_from_file` is key path for fileEntry with cas manager. If smoke case works, then coverage is expected.

That is point that new feature not opened in smoke.
[Args coverage](https://app.codecov.io/gh/dragonflyoss/nydus/pull/1507?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=dragonflyoss#diff-c3RvcmFnZS9zcmMvY2FjaGUvZGVkdXAvZGIucnM=)

2023-12-19 02:13 UTC, imeoer commented on smoke/tests/chunk_dedup_test.go
> +	tool.Verify(t, ctx, lowerLayer.FileTree)
We may need a way to check if the CAS works.

2023-12-19 02:19 UTC, imeoer commented on storage/src/cache/fscache/mod.rs
> +        let cas_mgr = if is_tarfs {
Maybe give a warnning message about conflict feature here.

2023-12-19 02:19 UTC, imeoer commented on storage/src/cache/filecache/mod.rs
> +        let cas_mgr = if mgr.cache_encrypted || mgr.cache_raw_data || is_tarfs {
Maybe give a warn message about conflict feature here.

2023-12-19 02:19 UTC, imeoer commented on docs/data-deduplication.md
> +## Chunk Deduplication by Using CAS as L2 Cache
This still seems to be an experimental feature, do we still need to consider the `cas.db` record recycling?

2024-05-28 18:48 UTC, jonoirwinrsa commented
Hi all, I tried out this feature and it seems to work as expected. Is there something preventing it from being merged?

2024-05-29 01:29 UTC, imeoer commented
> Hi all, I tried out this feature and it seems to work as expected. Is there something preventing it from being merged?

cc @jiangliu any updates we can continue? :)

2024-09-20 09:26 UTC, elijah-rou commented
what is the status of this PR? anything to do to help get it merged? :)

2024-10-23 14:53 UTC, Desiki-high commented
Complete in https://github.com/dragonflyoss/nydus/pull/1626.

2024-10-23 14:53 UTC, closed without merging