actions: remove unused var
dragonflyoss/image-service pull request #895
Opened 2022-11-25 09:16 UTC by liubin

If .github/workflows/release.yml the cnt is not used.

Signed-off-by: bin liu <bin@hyper.sh>

2022-11-25 10:53 UTC, imeoer approved these changes

2022-11-25 10:54 UTC, imeoer commented
@liubin Accidentally commit the `nydus-static-v2.1.1-linux-amd64.tgz`?

2022-11-25 10:55 UTC, imeoer requested changes
Holding

2022-11-25 14:40 UTC, liubin commented
> @liubin Accidentally commit the `nydus-static-v2.1.1-linux-amd64.tgz`?

Sorry, removed.

2022-11-26 05:12 UTC, jiangliu approved these changes

2022-11-26 13:36 UTC, imeoer approved these changes

2022-11-26 13:36 UTC, merged